{
  "contest": 216,
  "handle": "Sathish9098",
  "risk": "3",
  "title": "Possible Conditions That May Cause the sendOath External Function to Revert and the transfer failure",
  "issueId": 554,
  "issueUrl": "https://github.com/code-423n4/2023-02-ethos-findings/issues/554"
}